### ISSUE TITLE
When orientation changed session is broken

### ISSUE THREAD

**Issue by lordoftheflies** [lordoftheflies/mlm-portal#15]
On android any orientation changes implies a logout event.

**Comment by lordoftheflies** [comment]
Letiltottam az orientációváltást. Teszteld már le hw-n, hogy nálad is le van-e tiltva.

Döntsd el így jó lesz-e (mármint, ha nem vált orientációt) hosszútávon?

**Comment by Paradoxx88** [comment]
ja megnéztem nem müködik a döntögetés.
