### ISSUE TITLE
Böngészős hibalista

### ISSUE THREAD

**Issue by Paradoxx88** [lordoftheflies/mlm-portal#17]
1) Tartalom megosztás: Megosztás rész első fül: 
A kontaktok felvételénél. SZerintem nincs értelme kiratni fölülre hogy kinek küldöm el mivel amúgyis szürke lesz és végülis ott nem todom törölni a listábol csak ha rákatintok. Meg amúgyis szétcsúszik tőle. Maga az ablak.
1.1) Fura hogy az emailcimet irja ki nem a nevét.

2) Tartalom fül: hozzáadok egy szöveges tartalmat: Az első nyilas gombok nem működnek nem tudom ,hogy mit csinálnak da a végén a lefelé nyíl az teszi a dolgát, cserélgeti a sorrendet.
2.1) az igazitgatós gombok egyáltatlán nem akarnak müködni nekem.
2.2) ha hozzáadok egy új bármit képet videot stb: nincsenek definiálva a gombok
2.3) Link hozzáadását nem értem betudom irni ,hogy mi jelene
nyen meg de a lionket hova másolom be?
2.4) A föl le mozgató nyilak legyenek egymás mellett.

2.5) átkéne variálni a fájfeltöltés tartalom megosztást:
igy nézzen ki pls:

![sajattartalom](https://cloud.githubusercontent.com/assets/17258860/15193550/bdf72c92-17be-11e6-9353-7828dc6ba3db.png)

![fajfeltoltes](https://cloud.githubusercontent.com/assets/17258860/15193583/d935f5f6-17be-11e6-9b28-c69438366ecf.png)

Azzal a sárgával csináld kérlek amivel eddig is dolgozunk. Meg az efektek is ugyanazok legyenek.

3) A Tulajdonságok fülben:
Parent nem müködik vagy csak én nem tudom hozzáadni. Meg ilyen fura id is van a szöveg után.
3.1) nincs lokalizálva a menü title parents.

4)  Menük: beszéltünk róla de leirom. Jogosultság problémák vannak saját contetnek látom azokat amiket te csináltál. Meg a piszkozat is és még nincs lehetőség aktivvá tenni vagy paszivá tenni valamit.
4.1) A conteent fülei lehetnének olyanok ,hogy a akárhova katintasz belép. Ne a zöld hanem a piros bár legyen.
![menu](https://cloud.githubusercontent.com/assets/17258860/15194071/3f639228-17c1-11e6-8a23-62124b520034.png)

5) Postaláda: te megkaptad az üzeneteket? Mert nekem nem kerül bele az elküldött levelekbe.
6) Hálózat: Direkt üzentküldés gomb még nincs tudom beszéltük.
7) Eszközcsere ? csak rákatintok nem történik semmi.

**Comment by Paradoxx88** [comment]
network üzenetküldés van sry

**Comment by lordoftheflies** [comment]
1. #23

**Comment by lordoftheflies** [comment]
1.1 #24

**Comment by lordoftheflies** [comment]
2 #25

**Comment by lordoftheflies** [comment]
2.1 #26

**Comment by lordoftheflies** [comment]
2.2 #27

**Comment by lordoftheflies** [comment]
2.3 #28

**Comment by lordoftheflies** [comment]
2.4 #29

**Comment by lordoftheflies** [comment]
2.5 #30

**Comment by lordoftheflies** [comment]
1. #31

**Comment by lordoftheflies** [comment]
3.1 #32

**Comment by lordoftheflies** [comment]
6 #33

**Comment by lordoftheflies** [comment]
7 #34

**Comment by lordoftheflies** [comment]
5 #35

**Comment by lordoftheflies** [comment]
1. #36 #37
