### ISSUE TITLE
Telefonos hibalista

### ISSUE THREAD

**Issue by Paradoxx88** [lordoftheflies/mlm-portal#18]
1) Hülye hiba nem mindig tudod elhőhozni. De néha csak villog a menü. az a net kapcsolat?
2) Továbra is hülye hiba. Betöltésnél a betöltő kör valamiért hamarabb tünik el mint ,hogy bejönne a menü.
3) Sehol se tudok zoomolni
4) ha rányomok egy szövegre kap egy sárga keretett az micsoda?

**Comment by lordoftheflies** [comment]
Moved to:
1. #22 
2. #21 
3. #20
4. #19
