### ISSUE TITLE
Login layout

### ISSUE THREAD

**Issue by Paradoxx88** [lordoftheflies/mlm-portal#3]
![bejelentkezes](https://cloud.githubusercontent.com/assets/17258860/15073442/b7ee6582-1399-11e6-93cc-9c3cc95f93cd.png)

**Comment by lordoftheflies** [comment]
For device responsibility layout have to be changed to:
![image](https://cloud.githubusercontent.com/assets/4078632/15100202/b97c9698-156b-11e6-9545-af5afa5fe525.png)

**Comment by Paradoxx88** [comment]
SZerintem az elfelejtett jelszó nagyon rá van csúszva a emlékez rámra. Lehetne ugyananyi hely kihagyva köztük mint a sign-on közt van?

**Comment by lordoftheflies** [comment]
Ok.
