### ISSUE TITLE
Title field in the profile

### ISSUE THREAD

**Issue by lordoftheflies** [lordoftheflies/mlm-portal#6]
A Profilnál direkt nagy betükeel van kiirva a felhasználó neve? Nem ugy ahogy beregelt?

**Comment by lordoftheflies** [comment]
A material design az azt mondja, hogyha valami cím vagy gomb, akkor legyen kiskapitális.
Szóval szerintem ez nem hiba hanem feature. Már ha jó így.

**Comment by Paradoxx88** [comment]
SZerintem hülyén néz ki de maradjon. úgy is a kód határozza meg ki kicsioda.
